const CATALOGO = [
  { id: 'CAB-3X2.5', descripcion: 'Cable NYY 3x2,5mm²', unidad: 'm', precio: 0.85, categoria: 'cable', imagen: 'https://www.leroymerlin.es/productos/electrica/cables-y-conectores/cables/cable-nym-3x2-5mm2-100m-84700001.jpg' },
  { id: 'CAB-5X6', descripcion: 'Cable NYY 5x6mm²', unidad: 'm', precio: 1.90, categoria: 'cable', imagen: 'https://www.leroymerlin.es/productos/electrica/cables-y-conectores/cables/cable-nym-5x6mm2-100m-84700002.jpg' },
  { id: 'TUB-20', descripcion: 'Tubo corrugado Ø20mm', unidad: 'm', precio: 0.35, categoria: 'tubo', imagen: 'https://www.leroymerlin.es/productos/electrica/cables-y-conectores/tubos/tubo-corrugado-20mm-100m-84700003.jpg' },
  { id: 'CJA-ELEC', descripcion: 'Caja de empalmes IP65', unidad: 'ud', precio: 2.75, categoria: 'caja', imagen: 'https://www.leroymerlin.es/productos/electrica/cajas-y-elementos-de-proteccion/cajas/caja-empalmes-ip65-84700004.jpg' },
  { id: 'AUT-10A', descripcion: 'Interruptor automático 1P+N 10A curva C', unidad: 'ud', precio: 4.20, categoria: 'proteccion', imagen: 'https://www.leroymerlin.es/productos/electrica/cajas-y-elementos-de-proteccion/interruptores/interruptor-automatico-10a-84700005.jpg' },
  { id: 'AUT-20A', descripcion: 'Interruptor automático 1P+N 20A curva C', unidad: 'ud', precio: 4.60, categoria: 'proteccion', imagen: 'https://www.leroymerlin.es/productos/electrica/cajas-y-elementos-de-proteccion/interruptores/interruptor-automatico-20a-84700006.jpg' },
  { id: 'DIF-40A30', descripcion: 'Interruptor diferencial 40A 30mA', unidad: 'ud', precio: 11.50, categoria: 'proteccion', imagen: 'https://www.leroymerlin.es/productos/electrica/cajas-y-elementos-de-proteccion/interruptores/diferencial-40a-84700007.jpg' },
  { id: 'REG-12M', descripcion: 'Regleta de conexiones 12 módulos', unidad: 'ud', precio: 1.10, categoria: 'proteccion', imagen: 'https://www.leroymerlin.es/productos/electrica/cajas-y-elementos-de-proteccion/regletas/regleta-12-modulos-84700008.jpg' },
  { id: 'CUD-DOM', descripcion: 'Cuadro eléctrico 8-12 módulos superficie IP40', unidad: 'ud', precio: 9.50, categoria: 'proteccion', imagen: 'https://www.leroymerlin.es/productos/electrica/cajas-y-elementos-de-proteccion/cuadros/cuadro-electrico-12-modulos-84700009.jpg' },
  { id: 'LAM-LED18', descripcion: 'Pantalla LED 18W 120cm IP44', unidad: 'ud', precio: 12.30, categoria: 'iluminacion', imagen: 'https://www.leroymerlin.es/productos/iluminacion/iluminacion-interior/fluorescentes/pantalla-led-18w-84700010.jpg' }
];
